### ISSUE TITLE
How to fix `Error: error:0308010C:digital envelope routines::unsupported` error while working locally

### ISSUE THREAD

**Issue by skuchibhotla** [udacity/React-Fundamentals-C1-React-Contacts#7]
I am getting this error when I run this front-end project using the command `npm start` with the back-end project `reactnd-contacts-server2` running in the background. 

Here's a snapshot of the stack-trace: 

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/skuchibhotla/Projects/React-Fundamentals-C1-React-Contacts/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/skuchibhotla/Projects/React-Fundamentals-C1-React-Contacts/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/skuchibhotla/Projects/React-Fundamentals-C1-React-Contacts/node_modules/webpack/lib/NormalModule.js:471:10)
```

Any kind of help is appreciated. Thank you:)

**Comment by skuchibhotla** [comment]
Running with npm `9.8.0` and node `v20.5.0`.

**Comment by skuchibhotla** [comment]
I was able to fix this issue by updating the `react-scripts` version to `^5.0.1`, like what was mentioned in the PR https://github.com/udacity/React-Fundamentals-C1-React-Contacts/pull/5

Wanted to get this verified by anyone maintaining this repo.
